// export const BASE_URL: string = process.env.NODE_ENV === "development" ? "http://localhost:8080" : "https://vscode-puzzle.herokuapp.com";

export const BASE_URL = "https://vscode-puzzles.herokuapp.com";

export const TEMPLATE: string = `# {{ title }} (by [Puzzles](https://github.com/michaelfromyeg/vscode-puzzles))

Created: {{ date }}

Source: {{ source }}

ID: {{ id }}

## Puzzle

{{{ problem }}}
`;

const PYTHON: string = `# Auto-generated by Puzzles

# Solution

def solve():
  '''
  ...
  '''
  print('TODO')

if __name__ == 'main':
  solve()

# And don't forget to write your tests!

assert(...,...)

`;

const JAVASCRIPT: string = `// Auto-generated by Puzzles

// Solution

/*
 * ...
 */
function solve() {
  console.log('TODO');
}

// And don't forget to write your tests!

console.assert(...,...);

`;

const TYPESCRIPT: string = `// Auto-generated by Puzzles

// Solution

/*
 * ...
 */
const solve = () => {
  console.log('TODO');
}

// And don't forget to write your tests!

console.assert(...,...);

`;

const JAVA: string = `// Auto-generated by Puzzles

// Solution

public Main {
  public static void main(String[] args) {
    System.out.println("TODO");
  }
}
`;

const C: string = `// Auto-generated by Puzzles

// Solution

int main() {
  printf("TODO\\n");
  return 0;
}
`;

// [extension, content]
type FilePair = [string, string];

export const LANGUAGES: Record<string, FilePair> = {
  javascript: ["js", JAVASCRIPT],
  typescript: ["ts", TYPESCRIPT],
  python: ["py", PYTHON],
  java: ["java", JAVA],
  c: ["c", C]
};
