export const BASE_URL: string = "http://localhost:3000";

export const TEMPLATE: string = `# {{ title }} (by vscode-puzzle)

## from {{ source }}

{{{ problem }}}
`

export const PYTHON: string = `# Auto-generated by vscode-puzzle

# Solution

def solve():
  print('TODO')

if __name__ == 'main':
  solve()

# And don't forget to write your tests!

assert(...,...)

`